# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  #env:
  #MY_VAR: ${{ secrets.MY_VAR }}
  # ENV_MAIN_SECRET: '${{ secrets.ENV_MAIN_SECRET }}'
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: condition 1
        if: github.ref == 'refs/heads/main'
        run: echo "MY_VAR=${{ secrets.ENV_MAIN }}" >> "$GITHUB_ENV"
      
      - name: condition 1
        if: github.ref == 'refs/heads/dev'
        run: echo "MY_VAR=${{ secrets.ENV_DEV }}" >> "$GITHUB_ENV"

      - name: Main branch ?
        if: env.MY_VAR == 'main'
        run: echo ${{ env.MY_VAR }}

      - name: Dev branch ?
        if: env.MY_VAR == 'dev'
        run: echo "MY_VAR is DeV"
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
